blog/api/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('Visitor', views.Visitor, name='Visitorjson'),
    path('access', views.accessViews, name='access')
]

blog/blog/urls.py
from blog import views
from django.conf import settings
from django.conf.urls import static
import notifications.urls
from xadmin.plugins import xversion
from django.contrib import admin
from django.urls import path, include

import xadmin
xadmin.autodiscover()
xversion.register_models()
urlpatterns = [
    path('admin/', admin.site.urls),  # django原生后台
    # path('xadmin/', xadmin.site.urls),  # xadmin后台
    path('', include('index.urls')),  # 网站首页
    path('api/', include('api.urls')),  # api接口
    path('user/', include('user.urls')),  # 用户中心及其他用户操作
    path('search/', include('search.urls')),  # 站内搜索
    path('config/', include('set_config.urls')),  # 用户配置
    path('tools/', include('tools.urls')),  # 网站工具
    path('captcha/', include('captcha.urls')),  # 验证码接口
    path('tinymce/', include('tinymce.urls')),  # 固定写法，其实是映射到人家写好的应用
    path(
        'notifications/',
        include(
            notifications.urls,
            namespace='notifications')),
]

urlpatterns += static.static(settings.STATIC_URL,
                             document_root=settings.STATIC_ROOT)


handler400 = views.bad_request
handler403 = views.permission_denied
handler404 = views.page_not_found
handler500 = views.server_error

blog/notifications/urls.py
''' Django notification urls file '''
# -*- coding: utf-8 -*-
from distutils.version import StrictVersion  # pylint: disable=no-name-in-module,import-error

from django import get_version

from . import views

if StrictVersion(get_version()) >= StrictVersion('2.0'):
    from django.urls import re_path as pattern
else:
    from django.conf.urls import url as pattern


urlpatterns = [
    pattern(
        r'^$',
        views.AllNotificationsList.as_view(),
        name='all'),
    pattern(
        r'^unread/$',
        views.UnreadNotificationsList.as_view(),
        name='unread'),
    pattern(
        r'^mark-all-as-read/$',
        views.mark_all_as_read,
        name='mark_all_as_read'),
    pattern(
        r'^mark-as-read/(?P<slug>\d+)/$',
        views.mark_as_read,
        name='mark_as_read'),
    pattern(
        r'^mark-as-unread/(?P<slug>\d+)/$',
        views.mark_as_unread,
        name='mark_as_unread'),
    pattern(
        r'^delete/(?P<slug>\d+)/$',
        views.delete,
        name='delete'),
    pattern(
        r'^delete/all/$',
        views.deleteall,
        name='deleteall'),
    pattern(
        r'^delete/unread/$',
        views.deleteunread,
        name='deleteunread'),
    pattern(
        r'^api/unread_count/$',
        views.live_unread_notification_count,
        name='live_unread_notification_count'),
    pattern(
        r'^api/all_count/$',
        views.live_all_notification_count,
        name='live_all_notification_count'),
    pattern(
        r'^api/unread_list/$',
        views.live_unread_notification_list,
        name='live_unread_notification_list'),
    pattern(
        r'^api/all_list/',
        views.live_all_notification_list,
        name='live_all_notification_list'),
]

app_name = 'notifications'

blog/tools/urls.py
from . import views
from django.urls import path, include
# 设置首页的URL地址信息
urlpatterns = [
    path('post_new', views.NewVisew, name='new'),  # 新建文章
    path(
        'post_eidtor/<int:post_id>',
        views.EidtorVisew,
        name='eidtor'),
    # 编辑文章
    path('UploadFile', views.UploadFileView, name='Upload_file'),  # 上传文件
]

urlpatterns += [
    path('chat_free', views.chatfreeView, name='chat_free'),  # 菲菲聊天机器人
    path('chat_xiaoi', views.chatxiaoiView, name='chat_xiaoi'),  # 小艾聊天机器人
    path('chat_dandan', views.chatdandanView, name='chat_dandan'),  # 小艾聊天机器人
    path('ajax_chat/', include([
        path(
            'free',
            views.ajax_chat_free,
            name='ajax_chat_free'),
        # 菲菲聊天ajax接口
        path(
            'xiaoi',
            views.ajax_chat_xiaoi,
            name='ajax_chat_xiaoi'),
        # 小艾聊天ajax接口
        path(
            'dandan',
            views.ajax_chat_dandan,
            name='ajax_chat_dandan'),
        # 蛋蛋聊天ajax接口
    ])),  # 二级路由
    path('music', views.musicView, name='music'),  # 音乐解析
    path('video', views.videoView, name='video_vip'),  # 视频解析
    path(
        'images',
        views.ImageCompressionView,
        name="ImageCompression"),
    # 图片压缩
]

blog/tools/models.py
from django.db import models
from django.utils import timezone


class Access(models.Model):
    id = models.AutoField('序号', primary_key=True)
    date = models.DateTimeField('日期', default=timezone.now, max_length=125)
    num = models.IntegerField('访问量', default=0)

    def __str__(self):
        return self.num

    class Meta:
        # 设置Admin界面的显示内容
        verbose_name = '网站访问量列表'
        verbose_name_plural = '网站访问量列表'


class SetCtarl(models.Model):
    id = models.AutoField('序号', primary_key=True)
    name = models.CharField('名称', max_length=125, default="")
    is_start = models.BooleanField('是否开启', default=False)

    def __str__(self):
        return self.name

    class Meta:
        # 设置Admin界面的显示内容
        verbose_name = '网站设置控制列表'
        verbose_name_plural = '网站设置控制列表'

blog/tools/forms.py
from django import forms


class PostForm(forms.Form):
    title = forms .CharField(label='文章标题')
    content = forms.CharField(label='文章内容')
    type = forms.TypedChoiceField(label='文章类型',
                                  choices=(
                                      ('原创', '原创'),
                                      ('转载', '转载'),
                                      ('杂谈', '杂谈'),
                                  ),
                                  )


class UPfileForm(forms.Form):
    file = forms.FileField(label='文件')

blog/tools/views.py
import os
import platform
import threading
from .forms import *
import datetime
import pytz
import blog
import re
from index.models import Post
from blog import paginatorPage
from django.conf import settings
from django.contrib import messages
from django.http import JsonResponse
from blog_Plugin.images import get_img
from notifications.signals import notify
from index.views import get_notifications
from index.views import get_user, get_name
from django.template import RequestContext
from index.templatetags.index import getDC
from blog_Plugin.like import Unicode_or_chinese
from user.models import MyUser as User, UPfile, Attention
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, HttpResponse
from blog_Plugin.music import get_136Music, get_tencentMusic
from blog_Plugin.robot import get_reply_free, get_reply_xiaoi, get_reply_dandan


def sendNotify(request, user, post):
    attention_list = Attention.objects.filter(attention_id=user.id).all()
    for attention in attention_list:
        notify.send(
            get_notifications(),
            recipient=attention.user,
            level='info',
            verb='<a href="' +
            getDC(request) +
            '/post/' +
            str(
                post.id) +
            '">' +
            get_name(user) +
            '刚刚发布了《' +
            post.title +
            '》</a>')
    return 0


@login_required(login_url='/user/login')
def NewVisew(request):
    '''
    新建文章
    :param request: 客户端请求头
    :return: html页面或者跳转到主页
    '''
    form = PostForm()
    title__post = '发布文章'  # 按钮名称
    if request.method == 'POST':
        user = User.objects.get(id=request.user.id)
        if re.match(r'<script>.*?</script>', request.POST.get('content', '')):
            messages.error(request, '发布文章失败，检测提交js脚本')
            return redirect('/user/home')
        post = Post(title=request.POST.get('title', ''),
                    content=request.POST.get('content', ''),
                    user=user, time=datetime.datetime.now())
        post.save()
        t = threading.Thread(target=sendNotify, args=(request, user, post))
        t.start()
        messages.error(request, '发布文章成功，检测提交js脚本')
        return redirect('/user/home')
    return render(request, 'post_file.html', locals(), RequestContext(request))


@login_required(login_url='/user/login')
def EidtorVisew(request, post_id):
    '''
    修改文章
    :param request: 客户端请求头
    :param post_id: 博客文章id
    :return: html页面或者跳转到主页
    '''
    form = PostForm()
    title__post = '确定修改'  # 按钮名称
    post = Post.objects.get(id=post_id)
    user = get_user(request)
    if user != post.user:
        return redirect('/')  # 判断当前用户是否为此文章作者
    if request.method == 'POST':
        if re.match(r'<script>.*?</script>', request.POST.get('content', '')):
            messages.error(request, '修改失败，检测提交js脚本')
            return redirect('/user/home')
        post.title = request.POST.get('title', '')
        post.content = request.POST.get('content', '')
        post.save()
        messages.success(request, '修改成功')
        return redirect('/user/home')
    return render(request, 'post_file.html', locals(), RequestContext(request))


@login_required(login_url='/user/login')
def UploadFileView(request):
    '''
    上传文件
    :param request: 客户端请求头
    :return: html页面
    '''
    user = User.objects.get(id=request.user.id)
    if user.is_upload == 0:
        return redirect('/')  # 检测用户上传权限
    form = UPfileForm()
    page = request.GET.get('page', 1)
    if request.method == 'POST':
        file = request.FILES['file']
        name, filename = blog.randNmae() + '_' + file.name, file.name
        Upload_file, user = settings.MEDIA_ROOT_FILE + \
            name, User.objects.get(id=request.user.id)
        with open(Upload_file, 'wb') as f:
            for file_bytes in file.chunks():
                f.write(file_bytes)
        str = 'stat' if platform.system() != 'Windows'else ''  # UNIX和类UNIX(例如linux)系统会少四个字符
        upfile = UPfile(
            name=filename,
            file='/' +
            str +
            Upload_file.lstrip(
                settings.BASE_DIR),
            user=user,
            time=datetime.datetime.now(
                tz=pytz.timezone('UTC')))
        upfile.save()
        tips = '上传文件成功'
    upfile = UPfile.objects.filter(user=user).order_by('-time').all()
    post_num = len(upfile)
    paginator, pageInfo = paginatorPage(
        upfile, settings.HAYSTACK_SEARCH_RESULTS_PER_PAGE)
    return render(
        request,
        'UploadFile.html',
        locals(),
        RequestContext(request))


def chatfreeView(request):
    '''
    菲菲聊天机器人
    :param request: 客户端请求数据
    :return: html页面
    '''
    title = '菲菲'
    return render(request, 'chat.html', locals(), RequestContext(request))


def chatxiaoiView(request):
    '''
    小i聊天机器人
    :param request: 客户端请求数据
    :return: html页面
    '''
    title = '小i'
    return render(request, 'chat.html', locals(), RequestContext(request))


def chatdandanView(request):
    '''
    蛋蛋聊天机器人
    :param request: 客户端请求数据
    :return: html页面
    '''
    title = '蛋蛋'
    return render(request, 'chat.html', locals(), RequestContext(request))


def ajax_chat_free(request):
    '''
    聊天机器人ajax
    :param request: 客户端请求信息
    :return: 一段json信息
    '''
    res = {'status': 0, 'message': u'未知错误', 'data': ''}  # 定义错误信息
    if request.is_ajax():
        res['data'] = get_reply_free(request.GET['data'])  # 获取机器人返回的信息
        res['message'] = 'successful'
    return JsonResponse(res)


def ajax_chat_xiaoi(request):
    '''
    聊天机器人ajax
    :param request: 客户端请求信息
    :return: 一段json信息
    '''
    res = {'status': 0, 'message': '未知错误', 'data': ''}
    if request.is_ajax():
        res['data'] = get_reply_xiaoi(
            request.GET['data']).replace(
            '\\r',
            '').replace(
            '\\t',
            '').replace(
                '\\n',
            '')
        # 获取机器人返回的信息并删除一些不必要的符号
        res['message'] = 'successful'
    return JsonResponse(res)


def ajax_chat_dandan(request):
    '''
    聊天机器人ajax
    :param request: 客户端请求信息
    :return: 一段json信息
    '''
    res = {'status': 0, 'message': u'未知错误', 'data': ''}
    if request.is_ajax():
        getdata = request.GET['data']  # 获取传入的数据
        data = get_reply_dandan(getdata)  # 获取机器人返回的信息
        if getdata == "笑话" or getdata == "观音灵签" or getdata == "月老灵签" or getdata == "财神爷灵签":
            data = Unicode_or_chinese(data)  # 字体转中文
        res['data'] = data
        res['message'] = 'successful'
    return JsonResponse(res)


def musicView(request):
    '''
    输入音乐名称，播放歌曲
    :param request: 客户端请求头
    :return: html页面或json数据
    '''
    mp3 = True  # 和video共享一个html文件
    # 获取客户端请求的数据
    name = request.GET.get('name', '')  # 歌曲名字
    redirecton = int(request.GET.get('redirect', '0'))  # 放回数据类型
    website = request.GET.get('website', 'tencent').lower()  # 获取文件的
    if website == "netease".lower():
        if name:
            music_dict = get_136Music(name)  # 获取歌曲信息信息
            if redirecton == 2:
                return JsonResponse(music_dict)  # 返回json数据
            elif redirecton == 1:
                return redirect(music_dict['url'])  # 跳转歌曲下载地址
    elif website == "tencent".lower():
        if name:
            music_dict = get_tencentMusic(name)  # 获取歌曲信息信息
            if redirecton == 2:
                return JsonResponse(music_dict)  # 返回json数据
            elif redirecton == 1:
                return redirect(music_dict['url'])  # 跳转歌曲下载地址
    return render(request, 'play.html', locals(), RequestContext(request))


def videoView(request):
    '''
    输入视频url播放视频
    :param request: 客户端请求头
    :return: html页面
    '''
    url = request.GET.get('url', '')
    name = '视频解析'
    return render(request, 'play.html', locals(), RequestContext(request))


def ImageCompressionView(request):
    '''
    输入图片url压缩图片
    :param request: 客户端请求头
    :return: html页面或跳转到压缩后的图片url
    '''
    # 获取客户端请求的数据
    url = request.GET.get('url', '')
    redirecton = int(request.GET.get('redirect', 0))
    if url:
        if redirecton == 1:
            path = get_img(url)  # 进行图片压缩
            img = open(path, 'rb')
            response = HttpResponse(img.read(), content_type='image/png')
            # response['Content-Disposition'] = 'attachment; filename="' + path + '"'
            img.close()
            os.remove(path)  # 删除图片文件
            return response
        else:
            pathUrl = '/fun/images?redirect=1&url={}'.format(url)
    return render(
        request,
        'imagecompression.html',
        locals(),
        RequestContext(request))

blog/tools/templates/UploadFile.html
{% extends "title_base.html"  %}
{% block title %}上传文件{% endblock %}
{% block content_class %}col-xs-12 col-sm-9{% endblock %}
{% block content_left %}{% include 'manag_home_left.html' %}{% endblock %}
{% block content %}{% load staticfiles %}
    <div style="float: right;width: 100%;background-color: white;padding: 10px;border-radius: 5px">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <h3>上传文件</h3>
             <input class="file" id="file" name="file" placeholder="上传头像"  type="file">
            <div><input type="submit" value="开始上传"></div>
        </form>
        <div class="form-actions well well-sm">
        <h2>已上传的文件:{{ post_num }}个</h2>
        {% if post_num %}
            {% for upfile in pageInfo %}
                {% if not upfile.Prohibited %}
                    <a href="{{ upfile.file }}">
                        <div style="padding: 10px;word-break: break-all;word-wrap: break-word;background-color: #f5f5f5;border: 1px solid #ccc; border-radius: 4px;">
                            <div>{{ upfile.name }}</div><hr>
                            <div>{{ upfile.time }}</div>
                        </div>
                    </a>
                {% else %}
                    <div style="padding: 10px;word-break: break-all;word-wrap: break-word;background-color: #f5f5f5;border: 1px solid #ccc; border-radius: 4px;">
                         <h3>本文件因为{{ upfile.Prohibited_info}}违规已删除</h3>
                    </div>
                {% endif %}
            {% endfor %}
        {% else %}
            <div style="padding: 10px;word-break: break-all;word-wrap: break-word;background-color: #f5f5f5;border: 1px solid #ccc; border-radius: 4px;">
                <h3>你还没有上传过文件到服务器</h3>
            </div>
        {% endif %}
        </div>
        <div class="page-box">
            <div class="pagebar" id="pageBar" style="padding: 0 0 10px;">
                {% if pageInfo.has_previous %}
                <a href="{% url 'UploadFile'  %}?page={{ pageInfo.previous_page_number }}" class="prev" target="_self"><i></i>上一页</a>
                {% endif %}
                {% for page in pageInfo.paginator.page_range %}
                    {% if pageInfo.number == page %}
                        <span class="sel">{{ page }}</span>
                    {% else %}
                        <a href="{% url 'UploadFile'  %}?page={{ page }}" target="_self">{{ page }}</a>
                    {% endif %}
                {% endfor %}
                {% if pageInfo.has_next %}
                <a href="{% url 'UploadFile' %}?page={{ pageInfo.next_page_number }}" class="next" target="_self">下一页<i></i></a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

blog/tools/templates/chat.html
{% extends "title_base.html" %}
{% block title %}{{ title }}聊天机器人{% endblock %}
{% block content_class %}col-xs-12 col-sm-9{% endblock %}
{% block content_left %}{% include 'fun_left.html' %}{% endblock %}
{% block fun %}<li class="nav-item active"><a href="{% url 'chat_xiaoi'  %}">小玩意</a></li>{% endblock %}
{% block content %}{% load staticfiles %}
    <div style="margin: 20px;float: right;width: 100%;margin-top: 0px;background-color: white;padding: 10px;border-radius: 5px">
        <div id="div1" style="width: 100%;height: 400px;border:5px;background-color:#b4e2ff ;
        border-style: outset;overflow:auto;border-color: white">
            <style>#display li{list-style: none;}</style>
            <div style="width: 100%;">
                <ul id="display" style="width: 100%"><br/>
                    <li style="color: red">{{ title }}机器人:</li>
                    <li style="color: blue">{{ title }}机器人欢迎您的到来</li>
                    <hr/>
                </ul>
            </div>
        </div>
        <div style="margin-top: 5px;">
            <textarea style="width:80%;float: left;height: 80px" id="data" onkeydown="keySend(event);"></textarea>
            <input type="submit" style="float: left;height: 80px;width: 20%;" value="发送(按Ctrl+Enter发送)" onclick="send()" id ="submit">
        </div>
        <center>
            <p>接口仅提供学习交流，不能作为商业使用</p>
            <p>接口官网地址:
            {% if title == '菲菲' %}
               <a href="http://api.qingyunke.com/" target="_blank">http://api.qingyunke.com/</a>
            {% elif title == '蛋蛋'%}
                <a href="http://www.itpk.cn/" target="_blank">http://www.itpk.cn/</a>
            {% else %}
               <a href="http://www.xiaoi.com/" target="_blank">http://www.xiaoi.com/</a>
            {% endif %}
            </p>
        </center>
    </div>
{% endblock %}

{% block script %}
<script>
    function keySend(event) {
        if (event.ctrlKey && event.keyCode == 13) {
        send();
        }
    }
   function send() {
        var data =  $.trim($('#data').val());
        if(data == ''){
            ('#div1')[0].scrollTop ='';
            return 0;
        }
        var str = document.createElement('li'); // 生成一个 li元素
        var str2 = document.createElement('li');; // 生成一个 li元素
        var hr = document.createElement('hr'); // 生成一个 li元素
        var div = document.getElementById("display");
        //console.log(data);
        str.style.color='red';
        str2.style.color='blue';
        str.innerHTML = "我:"; // 设置元素的内容
        str2.innerHTML =data; // 设置元素的内容
        div.appendChild(str); // 添加到UL中去
        div.appendChild(str2); // 添加到UL中去
        div.appendChild(hr); // 添加到UL中去
        $('#div1')[0].scrollTop =$('#div1')[0].scrollHeight;
        $('#data')[0].value='';
        $.ajax({
            {% if title == '菲菲' %}
            url:"{% url 'ajax_chat_free'%}",
            {% elif title == '蛋蛋'%}
            url:"{% url 'ajax_chat_dandan'%}",
            {% else %}
            url:"{% url 'ajax_chat_xiaoi'%}",
            {% endif %}
            type:"GET",
            data:{data:data},
            success:function(data){
                //console.log("response success: ", data);
                var str = document.createElement('li'); // 生成一个 li元素
                var str2 = document.createElement('li');; // 生成一个 li元素
                var hr = document.createElement('hr'); // 生成一个 li元素
                str.style.color='red';
                str2.style.color='blue';
                str.innerHTML = "{{ title }}机器人:"; // 设置元素的内容
                str2.innerHTML =data['data']; // 设置元素的内容
                div.appendChild(str); // 添加到UL中去
                div.appendChild(str2); // 添加到UL中去
                div.appendChild(hr); // 添加到UL中去
                $('#div1')[0].scrollTop =$('#div1')[0].scrollHeight;
            },
            error:function(XMLHttpRequest, textStatus) {
                   //alert(XMLHttpRequest.status);//状态码
                   //alert(XMLHttpRequest.readyState);//状态
                   //alert(textStatus);//错误信息
             }
        });
    }
</script>
{% endblock %}

blog/tools/templates/fun_left.html
<div class="col-xs-12 col-sm-3" style="text-align: center;margin-bottom: 20px;" >
    <div class="col-xs-12 col-sm-12 sidebar-offcanvas" id="sidebar" style="text-align: center;">
        <div class="list-group">
            <a href="{% url 'chat_xiaoi' %}" class="list-group-item">小 i 机器人</a>
            <a href="{% url 'chat_free' %}" class="list-group-item">菲菲机器人</a>
            <a href="{% url 'chat_dandan' %}" class="list-group-item">蛋蛋机器人</a>
            <a href="{% url 'video_vip' %}" class="list-group-item">视频解析</a>
            <a href="{% url 'music' %}" class="list-group-item">音乐解析</a>
            <a href="{% url 'ImageCompression' %}" class="list-group-item">图片压缩</a>
        </div>
    </div>
</div>

blog/tools/templates/imagecompression.html
{% extends "title_base.html" %}
{% block title %}图片压缩{% endblock %}
{% block content_class %}col-xs-12 col-sm-9{% endblock %}
{% block content_left %}<strong>{% include 'fun_left.html' %}</strong>{% endblock %}
{% block fun %}<li class="nav-item active"><a href="{% url 'chat_xiaoi'  %}">小玩意</a></li>{% endblock %}
{% block content %}{% load staticfiles %}
    <div style="margin: 20px;float: right;width: 100%;margin-top: 0px;background-color: white;padding: 10px;border-radius: 5px">
        <form action="">
            <div style="width: 100%">
                <input type="text" name="url" placeholder="输入URL" style="width: 85%;"
                       value="{{ url }}" title="歌名：{{ value }}">
                <input type="submit" value="压缩" style="width: 10%;background: black;color: white;">
                <h2 style="text-align: center">当前功能没完成，属于半成品。</h2>
            </div>
        </form><br/>
        <center>{% if pathUrl %}
            <p>点击图片即可下载或者右键图片另存为</p>
            <a  target="_blank" href="{{ pathUrl }}"><img src="{{ pathUrl }}" width="100%" /></a>{% endif %}
        </center>
    </div>
{% endblock %}

blog/tools/templates/post_file.html
{% extends "title_base.html"  %}
{% block title %}新建文章{% endblock %}
{% block content_class %}col-xs-12 col-sm-9{% endblock %}
{% block content_left %}{% include 'manag_home_left.html' %}{% endblock %}
{% block content  %}{% load staticfiles %}
    <div style="width: 100%;float: right;background-color: white;padding: 10px;border-radius: 5px">
        <div style="width: 95%;margin: 0 20px;">
            <form class="form" action="" method="post">
                {% csrf_token %}
                <div>{{ form.title.label }}<input id="title" name="title" style="width: 100%" value="{{ post.title }}"></div><br/>
                <div>{{ form.type.label }}<select name="type" class="form-control required" id="id_type">
                      <option value="原创">原创文章</option>
                      <option value="转载">转载文章</option>
                      <option value="杂谈">杂谈文章</option>
                    </select>
                </div><br/>
                <div>{{ form.content.label }}<textarea id="content" name="content">{{ post.content }}</textarea></div><br/>
                <button type="submit" class="btn btn-primary btn-block">{{ title__post }}</button>
            </form>
        </div>
    </div>
{% endblock  %}
{% block style %}<link type="text/css" rel="stylesheet" href="{% static "css/prism.css" %}">{% endblock %}
{% block script  %}

<script src="{%  static 'js/prism.js' %}"></script>
<script src="{%  static 'tinymce/js/tinymce/tinymce.min.js' %}"></script>
<script>
    tinymce.init({
        //选择class为content的标签作为编辑器
        selector: '#content',
        //方向从左到右
        directionality:'ltr',
        //语言选择中文
        language: "zh_CN",
        //高度为400
        height:400,
        //工具栏上面的补丁按钮
        plugins: [
                'advlist autolink link image lists charmap print preview hr anchor pagebreak spellchecker',
                'searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking',
                'save table contextmenu directionality emoticons template paste textcolor',
                'codesample',
        ],
        //工具栏的补丁按钮
         toolbar: 'insertfile undo redo | \
         styleselect | \
         bold italic | \
         alignleft aligncenter alignright alignjustify | \
         bullist numlist outdent indent | \
         link image | \
         print preview media fullpage | \
         forecolor backcolor emoticons |\
         codesample fontsizeselect fullscreen',
        //字体大小
        fontsize_formats: '10pt 12pt 14pt 18pt 24pt 36pt',
        //按tab不换行
        nonbreaking_force_tab: true,
    });
</script>
{% endblock  %}