blog/api/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('Visitor', views.Visitor, name='Visitorjson'),
    path('access', views.accessViews, name='access')
]

blog/blog/urls.py
from blog import views
from django.conf import settings
from django.conf.urls import static
import notifications.urls
from xadmin.plugins import xversion
from django.contrib import admin
from django.urls import path, include

import xadmin
xadmin.autodiscover()
xversion.register_models()
urlpatterns = [
    path('admin/', admin.site.urls),  # django原生后台
    # path('xadmin/', xadmin.site.urls),  # xadmin后台
    path('', include('index.urls')),  # 网站首页
    path('api/', include('api.urls')),  # api接口
    path('user/', include('user.urls')),  # 用户中心及其他用户操作
    path('search/', include('search.urls')),  # 站内搜索
    path('config/', include('set_config.urls')),  # 用户配置
    path('tools/', include('tools.urls')),  # 网站工具
    path('captcha/', include('captcha.urls')),  # 验证码接口
    path('tinymce/', include('tinymce.urls')),  # 固定写法，其实是映射到人家写好的应用
    path(
        'notifications/',
        include(
            notifications.urls,
            namespace='notifications')),
]

urlpatterns += static.static(settings.STATIC_URL,
                             document_root=settings.STATIC_ROOT)


handler400 = views.bad_request
handler403 = views.permission_denied
handler404 = views.page_not_found
handler500 = views.server_error

blog/notifications/urls.py
''' Django notification urls file '''
# -*- coding: utf-8 -*-
from distutils.version import StrictVersion  # pylint: disable=no-name-in-module,import-error

from django import get_version

from . import views

if StrictVersion(get_version()) >= StrictVersion('2.0'):
    from django.urls import re_path as pattern
else:
    from django.conf.urls import url as pattern


urlpatterns = [
    pattern(
        r'^$',
        views.AllNotificationsList.as_view(),
        name='all'),
    pattern(
        r'^unread/$',
        views.UnreadNotificationsList.as_view(),
        name='unread'),
    pattern(
        r'^mark-all-as-read/$',
        views.mark_all_as_read,
        name='mark_all_as_read'),
    pattern(
        r'^mark-as-read/(?P<slug>\d+)/$',
        views.mark_as_read,
        name='mark_as_read'),
    pattern(
        r'^mark-as-unread/(?P<slug>\d+)/$',
        views.mark_as_unread,
        name='mark_as_unread'),
    pattern(
        r'^delete/(?P<slug>\d+)/$',
        views.delete,
        name='delete'),
    pattern(
        r'^delete/all/$',
        views.deleteall,
        name='deleteall'),
    pattern(
        r'^delete/unread/$',
        views.deleteunread,
        name='deleteunread'),
    pattern(
        r'^api/unread_count/$',
        views.live_unread_notification_count,
        name='live_unread_notification_count'),
    pattern(
        r'^api/all_count/$',
        views.live_all_notification_count,
        name='live_all_notification_count'),
    pattern(
        r'^api/unread_list/$',
        views.live_unread_notification_list,
        name='live_unread_notification_list'),
    pattern(
        r'^api/all_list/',
        views.live_all_notification_list,
        name='live_all_notification_list'),
]

app_name = 'notifications'

blog/notifications/views.py
# -*- coding: utf-8 -*-
''' Django Notifications exemple views '''
from distutils.version import StrictVersion  # pylint: disable=no-name-in-module,import-error

from django import get_version
from django.contrib.auth.decorators import login_required
from django.forms import model_to_dict
from django.shortcuts import get_object_or_404, redirect
from django.utils.decorators import method_decorator
from django.views.generic import ListView
from notifications import settings
from notifications.models import Notification
from notifications.utils import id2slug, slug2id
from notifications.settings import get_config

if StrictVersion(get_version()) >= StrictVersion('1.7.0'):
    from django.http import JsonResponse  # noqa
else:
    # Django 1.6 doesn't have a proper JsonResponse
    import json
    from django.http import HttpResponse  # noqa

    def date_handler(obj):
        return obj.isoformat() if hasattr(obj, 'isoformat') else obj

    def JsonResponse(data):  # noqa
        return HttpResponse(
            json.dumps(data, default=date_handler),
            content_type="application/json")


class NotificationViewList(ListView):
    template_name = 'notifications/list.html'
    context_object_name = 'notifications'
    paginate_by = settings.get_config()['PAGINATE_BY']

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(NotificationViewList, self).dispatch(
            request, *args, **kwargs)


class AllNotificationsList(NotificationViewList):
    """
    Index page for authenticated user
    """

    def get_queryset(self):
        if settings.get_config()['SOFT_DELETE']:
            qset = self.request.user.notifications.active()
        else:
            qset = self.request.user.notifications.all()
        return qset


class UnreadNotificationsList(NotificationViewList):

    def get_queryset(self):
        return self.request.user.notifications.unread()


@login_required
def mark_all_as_read(request):
    request.user.notifications.mark_all_as_read()

    _next = request.GET.get('next')

    if _next:
        return redirect(_next)
    return redirect('notifications:unread')


@login_required
def mark_as_read(request, slug=None):
    notification_id = slug2id(slug)

    notification = get_object_or_404(
        Notification, recipient=request.user, id=notification_id)
    notification.mark_as_read()

    _next = request.GET.get('next')

    if _next:
        return redirect(_next)

    return redirect('notifications:unread')


@login_required
def mark_as_unread(request, slug=None):
    notification_id = slug2id(slug)

    notification = get_object_or_404(
        Notification, recipient=request.user, id=notification_id)
    notification.mark_as_unread()

    _next = request.GET.get('next')

    if _next:
        return redirect(_next)

    return redirect('notifications:unread')


@login_required
def delete(request, slug=None):
    notification_id = slug2id(slug)

    notification = get_object_or_404(
        Notification, recipient=request.user, id=notification_id)

    if settings.get_config()['SOFT_DELETE']:
        notification.deleted = True
        notification.unread = False
        notification.save()
    else:
        notification.unread = False
        notification.save()
        notification.delete()

    _next = request.GET.get('next')

    if _next:
        return redirect(_next)

    return redirect('notifications:all')


@login_required
def deleteall(request):

    notifications = Notification.objects.filter(deleted=False)

    for notification in notifications:
        if settings.get_config()['SOFT_DELETE']:
            notification.deleted = True
            notification.unread = False
            notification.save()
        else:
            notification.unread = False
            notification.save()
            notification.delete()

    _next = request.GET.get('next')

    if _next:
        return redirect(_next)

    return redirect('notifications:all')


@login_required
def deleteunread(request):

    notifications = Notification.objects.filter(unread=False)

    for notification in notifications:
        if settings.get_config()['SOFT_DELETE']:
            notification.deleted = True
            notification.save()
        else:
            notification.delete()

    _next = request.GET.get('next')

    if _next:
        return redirect(_next)

    return redirect('notifications:all')


def live_unread_notification_count(request):
    try:
        user_is_authenticated = request.user.is_authenticated()
    except TypeError:  # Django >= 1.11
        user_is_authenticated = request.user.is_authenticated

    if not user_is_authenticated:
        data = {
            'unread_count': 0
        }
    else:
        data = {
            'unread_count': request.user.notifications.unread().count(),
        }
    return JsonResponse(data)


def live_unread_notification_list(request):
    ''' Return a json with a unread notification list '''
    try:
        user_is_authenticated = request.user.is_authenticated()
    except TypeError:  # Django >= 1.11
        user_is_authenticated = request.user.is_authenticated

    if not user_is_authenticated:
        data = {
            'unread_count': 0,
            'unread_list': []
        }
        return JsonResponse(data)

    default_num_to_fetch = get_config()['NUM_TO_FETCH']
    try:
        # If they don't specify, make it 5.
        num_to_fetch = request.GET.get('max', default_num_to_fetch)
        num_to_fetch = int(num_to_fetch)
        if not (1 <= num_to_fetch <= 100):
            num_to_fetch = default_num_to_fetch
    except ValueError:  # If casting to an int fails.
        num_to_fetch = default_num_to_fetch

    unread_list = []

    for notification in request.user.notifications.unread()[0:num_to_fetch]:
        struct = model_to_dict(notification)
        struct['slug'] = id2slug(notification.id)
        if notification.actor:
            struct['actor'] = str(notification.actor)
        if notification.target:
            struct['target'] = str(notification.target)
        if notification.action_object:
            struct['action_object'] = str(notification.action_object)
        if notification.data:
            struct['data'] = notification.data
        unread_list.append(struct)
        if request.GET.get('mark_as_read'):
            notification.mark_as_read()
    data = {
        'unread_count': request.user.notifications.unread().count(),
        'unread_list': unread_list
    }
    return JsonResponse(data)


def live_all_notification_list(request):
    ''' Return a json with a unread notification list '''
    try:
        user_is_authenticated = request.user.is_authenticated()
    except TypeError:  # Django >= 1.11
        user_is_authenticated = request.user.is_authenticated

    if not user_is_authenticated:
        data = {
            'all_count': 0,
            'all_list': []
        }
        return JsonResponse(data)

    default_num_to_fetch = get_config()['NUM_TO_FETCH']
    try:
        # If they don't specify, make it 5.
        num_to_fetch = request.GET.get('max', default_num_to_fetch)
        num_to_fetch = int(num_to_fetch)
        if not (1 <= num_to_fetch <= 100):
            num_to_fetch = default_num_to_fetch
    except ValueError:  # If casting to an int fails.
        num_to_fetch = default_num_to_fetch

    all_list = []

    for notification in request.user.notifications.all()[0:num_to_fetch]:
        struct = model_to_dict(notification)
        struct['slug'] = id2slug(notification.id)
        if notification.actor:
            struct['actor'] = str(notification.actor)
        if notification.target:
            struct['target'] = str(notification.target)
        if notification.action_object:
            struct['action_object'] = str(notification.action_object)
        if notification.data:
            struct['data'] = notification.data
        all_list.append(struct)
        if request.GET.get('mark_as_read'):
            notification.mark_as_read()
    data = {
        'all_count': request.user.notifications.count(),
        'all_list': all_list
    }
    return JsonResponse(data)


def live_all_notification_count(request):
    try:
        user_is_authenticated = request.user.is_authenticated()
    except TypeError:  # Django >= 1.11
        user_is_authenticated = request.user.is_authenticated

    if not user_is_authenticated:
        data = {
            'all_count': 0
        }
    else:
        data = {
            'all_count': request.user.notifications.count(),
        }
    return JsonResponse(data)

blog/notifications/templates/notifications/list.html
{% extends "title_base.html"  %}{% load notifications_tags %}
{% block title %}{% if request.get_full_path != '/notifications/'%}未读信息{% else %}全部信息{% endif %}{% endblock %}
{% block search %}{% endblock %}
{% block message %}
    <li class="nav-item active" style="margin-left: 10px;" title="消息通知">
        <a href="{% url 'notifications:all'  %}">
            <span class="glyphicon glyphicon-flag" aria-hidden="true"></span>
            {% notifications_unread as unread_count %}
            <span style="background-color:#d9534f;color: white;border-radius: 10px;" id="num_mess">
                {% if unread_count %}{{unread_count}}{% endif %}</span>
        </a>
    </li>
{% endblock %}
{% block content  %}{% load staticfiles %}
    <ul class="notifications">
        <button type="button" class="default btn btn-success hide-xs">
            {% if request.get_full_path != '/notifications/'%}
            <a href="{% url 'notifications:all' %}"  style="color: white;text-decoration: none;">查看所有信息</a>{% else %}
            <a href="{% url 'notifications:unread' %}"  style="color: white;text-decoration: none;">查看未读信息</a>{% endif %}
        </button>
        <button type="button" class="default btn btn-primary hide-xs">
            <a href="{% url 'notifications:mark_all_as_read' %}"  style="color: white;text-decoration: none;">全部标记已读</a>
        </button>
        <button type="button" class="btn btn-danger default hide-xs">
            {% if request.get_full_path != '/notifications/'%}
            <a href="{% url 'notifications:deleteunread' %}"  style="color: white;text-decoration: none;">删除已读信息</a>{% else %}
            <a href="{% url 'notifications:deleteall' %}"  style="color: white;text-decoration: none;">删除全部信息</a>{% endif %}
        </button><br/><br/>
        {% if notifications %}
            {% for notice in notifications %}
                {% include 'notifications/notice.html' %}
            {% endfor %}
        {% else %}
            <h2>信息列表为空</h2>
        {% endif %}

    </ul>
{% endblock %}

blog/notifications/templates/notifications/notice.html
<div class="alert alert-block alert-{{ notice.level }}">
  <a class="close pull-right" title="删除此消息"
     href="{% url 'notifications:delete' notice.slug %}">
{#    <i class="icon-close"></i>glyphicon glyphicon-remove#}
    <i class="glyphicon glyphicon-trash"></i>&ensp;
  </a>

  <a class="close pull-right" title="设置为已读"
     href="{% url 'notifications:mark_as_read' notice.slug %}">
{#    <i class="icon-close"></i>glyphicon glyphicon-remove#}
    <i class="glyphicon glyphicon-remove"></i>
  </a>

  <h4>
    <i class="icon-mail{% if notice.unread %}-alt{% endif %}"></i>
{#  {% firstof notice.actor.get_short_name notice.actor.get_username %}:#}
{#    {{ notice.actor }}#}
    {{ notice.verb | safe }}
    {% if notice.target %}
      of {{ notice.target }}
    {% endif %}
  </h4>
  
  <p>{{ notice.timesince }}</p>
  
{#  <p>{{ notice.description | linebreaksbr }}</p>#}
{#  #}
{#  <div class="notice-actions">#}
{#    {% for action in notice.data.actions %}#}
{#      <a class="btn" href="{{ action.href }}">{{ action.title }}</a>#}
{#    {% endfor %}#}
{#  </div>#}
</div>

blog/notifications/templates/notifications/test_tags.html
{% load notifications_tags %}

{% register_notify_callbacks callbacks='fill_notification_menu,fill_notification_badge' %}

{% notifications_unread as unread %}
{{ unread }}
{% live_notify_badge %}
{% live_notify_list %}