blog/api/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('Visitor', views.Visitor, name='Visitorjson'),
    path('access', views.accessViews, name='access')
]

blog/blog/urls.py
from blog import views
from django.conf import settings
from django.conf.urls import static
import notifications.urls
from xadmin.plugins import xversion
from django.contrib import admin
from django.urls import path, include

import xadmin
xadmin.autodiscover()
xversion.register_models()
urlpatterns = [
    path('admin/', admin.site.urls),  # django原生后台
    # path('xadmin/', xadmin.site.urls),  # xadmin后台
    path('', include('index.urls')),  # 网站首页
    path('api/', include('api.urls')),  # api接口
    path('user/', include('user.urls')),  # 用户中心及其他用户操作
    path('search/', include('search.urls')),  # 站内搜索
    path('config/', include('set_config.urls')),  # 用户配置
    path('tools/', include('tools.urls')),  # 网站工具
    path('captcha/', include('captcha.urls')),  # 验证码接口
    path('tinymce/', include('tinymce.urls')),  # 固定写法，其实是映射到人家写好的应用
    path(
        'notifications/',
        include(
            notifications.urls,
            namespace='notifications')),
]

urlpatterns += static.static(settings.STATIC_URL,
                             document_root=settings.STATIC_ROOT)


handler400 = views.bad_request
handler403 = views.permission_denied
handler404 = views.page_not_found
handler500 = views.server_error

blog/notifications/urls.py
''' Django notification urls file '''
# -*- coding: utf-8 -*-
from distutils.version import StrictVersion  # pylint: disable=no-name-in-module,import-error

from django import get_version

from . import views

if StrictVersion(get_version()) >= StrictVersion('2.0'):
    from django.urls import re_path as pattern
else:
    from django.conf.urls import url as pattern


urlpatterns = [
    pattern(
        r'^$',
        views.AllNotificationsList.as_view(),
        name='all'),
    pattern(
        r'^unread/$',
        views.UnreadNotificationsList.as_view(),
        name='unread'),
    pattern(
        r'^mark-all-as-read/$',
        views.mark_all_as_read,
        name='mark_all_as_read'),
    pattern(
        r'^mark-as-read/(?P<slug>\d+)/$',
        views.mark_as_read,
        name='mark_as_read'),
    pattern(
        r'^mark-as-unread/(?P<slug>\d+)/$',
        views.mark_as_unread,
        name='mark_as_unread'),
    pattern(
        r'^delete/(?P<slug>\d+)/$',
        views.delete,
        name='delete'),
    pattern(
        r'^delete/all/$',
        views.deleteall,
        name='deleteall'),
    pattern(
        r'^delete/unread/$',
        views.deleteunread,
        name='deleteunread'),
    pattern(
        r'^api/unread_count/$',
        views.live_unread_notification_count,
        name='live_unread_notification_count'),
    pattern(
        r'^api/all_count/$',
        views.live_all_notification_count,
        name='live_all_notification_count'),
    pattern(
        r'^api/unread_list/$',
        views.live_unread_notification_list,
        name='live_unread_notification_list'),
    pattern(
        r'^api/all_list/',
        views.live_all_notification_list,
        name='live_all_notification_list'),
]

app_name = 'notifications'

blog/set_config/urls.py
from . import views
from django.urls import path
# 设置首页的URL地址信息
urlpatterns = [
    path(
        'edit_gravatar',
        views.edit_gravatarView,
        name='edit_gravatar'),
    # 更改头像
    path(
        'edit_profile',
        views.edit_profileView,
        name='edit_profile'),
    # 修改个人信息
    path(
        'collection_management',
        views.collection_managementView,
        name='collection_management'),
    # 收藏文章管理
    path(
        'attention_management',
        views.attention_managementView,
        name='attention_management'),
    # 关注博主管理
]

blog/set_config/models.py
from django.db import models

# Create your models here.

blog/set_config/forms.py
from django import forms


class ProfileForm(forms.Form):
    interest = forms.CharField(label='兴趣')
    aims = forms.CharField(label='最近目标')
    motto = forms.CharField(label='座右铭')
    self_reprot = forms.CharField(label='自我介绍')

blog/set_config/views.py
from .forms import *
import os
import blog
import platform
from django.conf import settings
from index.models import Collection
from user.models import MyUser as User
from user.models import Profile, Attention
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from blog import paginatorPage
from django.template import RequestContext

# Create your views here.
@login_required(login_url='/user/login')
def edit_profileView(request):
    '''
    修改个人信息
    :param request: 客户端请求头
    :return: hrml页面
    '''
    form = ProfileForm()
    user = User.objects.get(id=request.user.id)
    profile = Profile.objects.filter(user=user).first()
    if not profile:
        profile = Profile(user=user, self_reprot='这个人很懒，什么也没有写！')  # 防止出现错误
    if request.method == 'POST':
        profile.interest = request.POST.get('interest', '')
        profile.aims = request.POST.get('aims', '')
        profile.motto = request.POST.get('motto', '')
        profile.self_reprot = request.POST.get('self_reprot', '')
        user.first_name = request.POST.get('first_name', '')
        user.last_name = request.POST.get('last_name', '')
        user.save()
        profile.save()
        tips = '修改个人信息成功'
    return render(
        request,
        'edit_profile.html',
        locals(),
        RequestContext(request))


@login_required(login_url='/user/login')
def edit_gravatarView(request):
    '''
    更改头像
    :param request: 客户端请求头
    :return: hrml页面
    '''
    file_url = request.user.avatar
    if request.method == 'POST':
        photo = request.FILES['photo']
        name = blog.randNmae() + os.path.splitext(photo.name)[1]
        photo_file = settings.MEDIA_ROOT + name
        with open(photo_file, 'wb') as f:
            for fimg in photo.chunks():
                f.write(fimg)
        user = User.objects.filter(id=request.user.id).first()
        # 删除以前的头像
        if platform.system() != 'Windows':
            os.system('rm -rf ' + settings.BASE_DIR + user.avatar)
        else:
            os.remove(settings.BASE_DIR + user.avatar)
        # UNIX和类UNIX(例如linux)系统会少四个字符
        if platform.system() != 'Windows':
            str = 'stat'
        else:
            str = ''
        user.avatar = '/' + str + photo_file.lstrip(settings.BASE_DIR)
        user.save()
        tips = '上传头像成功'
    return render(
        request,
        'edit_gravatar.html',
        locals(),
        RequestContext(request))


@login_required(login_url='/user/login')
def collection_managementView(request):
    '''
    收藏文章管理
    :param request: 客户端请求头
    :return: hrml页面
    '''
    title = '收藏的文章'
    page = request.GET.get('page', 1)
    root_user = User.objects.get(id=request.user.id)
    collection_list = Collection.objects.filter(user=root_user).all()
    paginator, pageInfo = paginatorPage(
        collection_list, settings.HAYSTACK_SEARCH_RESULTS_PER_PAGE, page)
    return render(
        request,
        'collection_manag.html',
        locals(),
        RequestContext(request))


@login_required(login_url='/user/login')
def attention_managementView(request):
    '''
    关注博主管理
    :param request: 客户端请求头
    :return: hrml页面
    '''
    title = '关注的博主'
    page = request.GET.get('page', 1)
    root_user = User.objects.get(id=request.user.id)
    attention_list = Attention.objects.filter(user=root_user).all()
    for i in attention_list:
        i.attention_id = User.objects.filter(id=i.attention_id).get()
    paginator, pageInfo = paginatorPage(
        attention_list, settings.HAYSTACK_SEARCH_RESULTS_PER_PAGE, page)
    return render(
        request,
        'attention_manag.html',
        locals(),
        RequestContext(request))

blog/set_config/templates/attention_manag.html
{% extends "title_base.html"  %}
{% block title %}{{ title }}{% endblock %}
{% block content_class %}col-xs-12 col-sm-9{% endblock %}
{% block content_left %}{% include 'manag_home_left.html' %}{% endblock %}
{% block content  %}{% load staticfiles %}
    {% if pageInfo %}
        {% for item in pageInfo %}
            {% if item.is_attention %}
                <a href="{% url 'user' %}?uid={{ item.attention_id.id }}">
                    <div class="navbar-collapse collapse" style="width: 100%">
                        <div class="form-actions well well-sm" style="font-size: 1.2em;color: blue">
                            <img src="{{ item.attention_id.avatar }}" width="30px" height="30px"
                                 style="border:2px solid;border-radius:10px;">
                                用户名：{% firstof item.attention_id.get_short_name item.attention_id.get_username %}
                        </div>
                    </div>
                </a>
            {% endif %}
        {% endfor %}
    {% else %}
        <div class="navbar-collapse collapse" style="float: left;width: 82%">
            <div class="form-actions well well-sm" style="font-size: 1.2em;color: blue">
                   找不到任何信息
            </div>
        </div>
    {% endif %}
        <div class="page-box" style="width: 80%;float: left;">
            <div class="pagebar" id="pageBar" style="padding: 0 0 10px;">
                {% if pageInfo.has_previous %}
                <a href="{% url 'attention_management' %}?page={{ pageInfo.previous_page_number }}" class="prev" target="_self"
                    style="background-color: #8C8C8C"><i></i>上一页</a>
                {% endif %}
                {% for page in pageInfo.paginator.page_range %}
                    {% if pageInfo.number == page %}
                        <span class="sel">{{ page }}</span>
                    {% else %}
                        <a href="{% url 'attention_management' %}?page={{ page }}" target="_self" style="background-color: #8C8C8C">{{ page }}</a>
                    {% endif %}
                {% endfor %}

                {% if pageInfo.has_next %}
                <a href="{% url 'attention_management'  %}?page={{ pageInfo.next_page_number }}" class="next" target="_self"
                    style="background-color: #8C8C8C">下一页<i></i></a>
                {% endif %}
            </div>
        </div>
{% endblock  %}

blog/set_config/templates/collection_manag.html
{% extends "title_base.html"  %}
{% block title %}{{ title }}{% endblock %}
{% block content_class %}col-xs-12 col-sm-9{% endblock %}
{% block content_left %}{% include 'manag_home_left.html' %}{% endblock %}
{% block content  %}{% load staticfiles %}
    {% if pageInfo %}
        {% for item in pageInfo %}
            {% if item.is_collection %}
                <a href="{% url 'post' item.post.id %}">
                    <div class="navbar-collapse collapse" style="width: 100%">
                        <div class="form-actions well well-sm" style="font-size: 1.2em;color: blue">
                            标题：【{{ item.post.type }}】{{ item.post.title }}<br/>
                            作者：{% firstof user.get_short_name user.get_username %}<br/>
                        </div>
                    </div>
                </a>
            {% endif %}
        {% endfor %}
    {% else %}
        <div class="navbar-collapse collapse" style="float: left;width: 82%">
            <div class="form-actions well well-sm" style="font-size: 1.2em;color: blue">
                   找不到任何信息
            </div>
        </div>
    {% endif %}
        <div class="page-box" style="width: 80%;float: left;">
            <div class="pagebar" id="pageBar" style="padding: 0 0 10px;">
                {% if pageInfo.has_previous %}
                <a href="{% url 'collection_management' %}?page={{ pageInfo.previous_page_number }}" class="prev" target="_self"
                    style="background-color: #8C8C8C"><i></i>上一页</a>
                {% endif %}
                {% for page in pageInfo.paginator.page_range %}
                    {% if pageInfo.number == page %}
                        <span class="sel">{{ page }}</span>
                    {% else %}
                        <a href="{% url 'collection_management' %}?page={{ page }}" target="_self" style="background-color: #8C8C8C">{{ page }}</a>
                    {% endif %}
                {% endfor %}

                {% if pageInfo.has_next %}
                <a href="{% url 'collection_management' %}?page={{ pageInfo.next_page_number }}" class="next" target="_self"
                    style="background-color: #8C8C8C">下一页<i></i></a>
                {% endif %}
            </div>
        </div>
{% endblock  %}

blog/set_config/templates/edit_gravatar.html
{% extends "title_base.html"  %}
{% block title %}更换头像{% endblock %}
{% block content_class %}col-xs-12 col-sm-9{% endblock %}
{% block content_left %}{% include 'manag_home_left.html' %}{% endblock %}
{% block content %}
    <div style="width: 100%;float: right;background-color: white;padding: 10px;border-radius: 5px">
        <div style="padding-left: 10px;">
            <div style="margin: 0 20px;">
                <form action="" method="POST" enctype="multipart/form-data" style="margin-bottom: 8px;margin-left: 5px">
                    {% csrf_token %}
                     <div class="page-header"><h2>头像展览板~</h2></div>
                     <a class="btn btn-success upload" placeholder="上传头像" ><p id="show_gt">选择您要上传的头像~</p>
                         <input class="change" id="photo" name="photo" onchange="c()" placeholder="上传头像" required type="file">
                     </a><br/>
                     {% if user.avatar %}
                     <br><img src="{{ user.avatar }}" width="256" height="256">
                     {% endif %}
                     <a class="btn btn-success"><-之前 之后-></a>
                     <img src="{{ user.avatar }}" id='show' width="256" height="256"><br/><br/>
                     <input class="btn btn-primary" id="submit" name="submit" type="submit" value="确认上传">
                </form>
            </div>
        </div>
    </div>
<script type="text/javascript">
    function c () {
        var gt=document.getElementById('show_gt');
        gt.innerText = '已选中图片~'
        var r= new FileReader();
        f=document.getElementById('photo').files[0];
        r.readAsDataURL(f);
        r.onload=function  (e) {
            document.getElementById('show').src=this.result;
        };
    }
</script>
<style  type="text/css">
.upload{padding: 5px 10px;height: 40px;line-height: 30px;position: relative;
    border: 1px solid #999;text-decoration: none;text-align:center;color: #fff;}
.change{position: absolute;overflow: hidden;right: 0;top: 0;opacity: 0;}
</style>
{% endblock %}

blog/set_config/templates/edit_profile.html
{% extends "title_base.html"  %}
{% block title %}修改个人信息{% endblock %}
{% block content_class %}col-xs-12 col-sm-9{% endblock %}
{% block content_left %}{% include 'manag_home_left.html' %}{% endblock %}
{% block content %}{% load staticfiles %}
    <div style="width: 100%;float: right;background-color: white;padding: 10px;border-radius: 5px">
        <form class="exform" enctype="" action="" method="post" id="profile_form">
            {% csrf_token %}
            <div class="form-container row clearfix">
                <div class="formColumn column form-column full col col-sm-12 form-horizontal ui-sortable" span="12" horizontal="">
                    <div class="panel panel-default fieldset unsort no_title">
                        <div class="panel-heading">
                            <i class="icon fa fa-chevron-up chevron">个人信息</i>
                            <h3 class="panel-title"></h3>
                        </div>
                        <div class="panel-body">
                            <div id="div_id_interest" class="form-group">
                                <label for="id_interest" class="control-label">名字</label>
                                <div class="controls">
                                    <input type="text" name="first_name" value="{{ user.first_name }}" class="text-field admintextinputwidget form-control" maxlength="30" id="id_first_name">
                                </div>
                            </div>
                            <div id="div_first_name" class="form-group">
                                <label for="first_name" class="control-label">姓氏</label>
                                <div class="controls">
                                    <input type="text" name="last_name" value="{{ user.last_name }}" class="text-field admintextinputwidget form-control" maxlength="255" id="id_motto">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="form-container row clearfix">
                <div class="formColumn column form-column full col col-sm-12 form-horizontal ui-sortable" span="12" horizontal="">
                    <div class="panel panel-default fieldset unsort no_title">
                        <div class="panel-heading">
                            <i class="icon fa fa-chevron-up chevron">其他</i>
                            <h3 class="panel-title"></h3>
                        </div>
                        <div class="panel-body">
                            <div id="div_id_interest" class="form-group">
                                <label for="id_interest" class="control-label">兴趣</label>
                                <div class="controls">
                                    <input type="text" name="interest" value="{{ profile.interest }}" class="text-field admintextinputwidget form-control" maxlength="255" id="id_interest">
                                </div>
                            </div>
                            <div id="div_id_aims" class="form-group">
                                <label for="id_aims" class="control-label">最近目标</label>
                                <div class="controls">
                                    <input type="text" name="aims" value="{{ profile.aims }}" class="text-field admintextinputwidget form-control" maxlength="255" id="id_aims">
                                </div>
                            </div>
                            <div id="div_id_motto" class="form-group">
                                <label for="id_motto" class="control-label">座右铭</label>
                                <div class="controls">
                                    <input type="text" name="motto" value="{{ profile.motto }}" class="text-field admintextinputwidget form-control" maxlength="255" id="id_motto">
                                </div>
                            </div>
                            <div id="div_id_self_reprot" class="form-group">
                                <label for="id_self_reprot" class="control-label">自我介绍</label>
                                <div class="controls">
                                    <input type="text" name="self_reprot" value="{{ profile.self_reprot }}" class="text-field admintextinputwidget form-control" maxlength="1024" id="id_self_reprot">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <button type="submit" class="default btn btn-primary hide-xs" name="_save" style="width: 100%;"><i class="fa fa-save"></i> 保存</button>
        </form>
    </div>
{% endblock %}